[green_agent]
agentbeats_id = "019bc4d7-f7b1-7760-a5c0-f8e94f9ef122"
env = { NEBIUS_API_KEY = "${NEBIUS_API_KEY}" }

[[participants]]
agentbeats_id = "019bf87b-0c78-7a32-99f5-ca45fa453157"
name = "supply_chain_planning_agent"
env = { NEBIUS_API_KEY = "${NEBIUS_API_KEY}" }

[config]
# Add your assessment config here
