[green_agent]
agentbeats_id = "019bc4d7-f7b1-7760-a5c0-f8e94f9ef122"
env = {}

[[participants]]
agentbeats_id = "019bc4dd-7e76-75f1-be6b-1810ee3986f1"
name = "supply_chain_planning_agent"
env = {GEMINI_API_KEY = ${{ secrets.GEMINI_API_KEY }}} 

[config]
# Add your assessment config here
