[green_agent]
agentbeats_id = "019bc4d7-f7b1-7760-a5c0-f8e94f9ef122"
env = {}

[[participants]]
agentbeats_id = ""
name = "supply_chain_planning_agent"
env = {}

[config]
# Add your assessment config here
